### ISSUE TITLE
Error while setting up platform energyeasy

### ISSUE THREAD

**Issue by mlevit** [mvandersteen/ha-jemenaoutlook#1]
Getting the following stack trace.

My sensor data is as per your example with my username and password added. My username is an email address so I've enclosed the username with single quotes (').

I'm using this for https://energyeasy.ue.com.au/ which is using the same platform as https://electricityoutlook.jemena.com.au/

The only thing I've modified is `HOST = 'https://energyeasy.ue.com.au'`.

```
2018-09-07 11:54:44 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up platform energyeasy
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/homeassistant/helpers/entity_platform.py", line 128, in _async_setup_platform
    SLOW_SETUP_MAX_WAIT, loop=hass.loop)
  File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sensor/energyeasy.py", line 148, in setup_platform
    jemenaoutlook_data.get_data()
  File "/config/custom_components/sensor/energyeasy.py", line 236, in get_data
    self._fetch_data()
  File "/config/custom_components/sensor/energyeasy.py", line 228, in _fetch_data
    self.client.fetch_data()
  File "/config/custom_components/sensor/energyeasy.py", line 502, in fetch_data
    self._data.update(self._get_tariffs())
  File "/config/custom_components/sensor/energyeasy.py", line 326, in _get_tariffs
    "controlled_load_cost": self._strip_currency(data["controlledLoadCost"]),
KeyError: 'controlledLoadCost'
```

**Comment by HappySl0th** [comment]
How did you solve this? I am currently facing a similar problem
