### ISSUE TITLE
Component Stopped working, NoneType Data.

### ISSUE THREAD

**Issue by thehaxxa** [mvandersteen/ha-jemenaoutlook#3]
Using the Energy Easy component based on the same code base, as of 07/01/2020 the component no longer works:

`Error while setting up platform energyeasy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 150, in _async_setup_platform
    await asyncio.wait_for(asyncio.shield(task), SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/energyeasy/sensor.py", line 156, in setup_platform
    sensors.append(EnergyEasySensor(energyeasy_data, variable, name))
  File "/config/custom_components/energyeasy/sensor.py", line 180, in __init__
    self._state = round(self.energyeasy_data.data.get(self.type, 0.0), 2)
TypeError: type NoneType doesn't define __round__ method`

Happy to debug or post any information as needed.

**Comment by igorpolsh** [comment]
Had the same error, strangely enough, I found a wrong indent on line 164 in sensor.py (def __init__(self, energyeasy_data, sensor_type, name):).

The function declaration was indented twice instead of once (under the class). 

Have a look if yours is the same, back off one indentation and see if it helps. 

Do let me know if it helps, i'm curious if its the same issue as I had.

**Comment by JinksKid** [comment]
I have the same issue. I think it has somthing to do with jemena having no data on "today" in the morning as it works fine in the afternoon until midnight.
